import dedent from "ts-dedent";

export const htmlFileContent = dedent`
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="./styles.css" />
    <script src="./app.js" async defer></script>
    <title>Document</title>
  </head>
  <body>
    <!-- Enjoy your day! 😃 -->
  </body>
</html>
`;

export const cssFileContent = dedent`
body {
  padding: 0;
  background-color: #fafafa;
}
`;

export const jsFileContent = dedent`
console.log("Generated by Static Boiler Dish!");
`;
